name: FoodBasket Backend CI/CD (Rust)

permissions:
  contents: write
  packages: write

on:
  push:
    paths:
      - apps/backend-rs/**
  pull_request:
    paths:
      - apps/backend-rs/**
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Don't truncate commit

      - uses: wagoid/commitlint-github-action@v6
        name: Commitlint

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        name: Setup Rust
        with:
          rust-src-dir: ./apps/backend-rs
          components: clippy, rustfmt

      - name: Check formatting
        working-directory: apps/backend-rs
        run: cargo fmt --check

      - name: Lint
        working-directory: apps/backend-rs
        run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    name: Test
    needs: ["lint"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        name: Setup Rust
        with:
          rust-src-dir: ./apps/backend-rs

      - name: Test
        working-directory: apps/backend-rs
        run: |
          cargo test

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: ["test"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        name: Setup Rust
        with:
          rust-src-dir: ./apps/backend-rs

      - name: Build
        working-directory: apps/backend-rs
        run: cargo build --release

  docker:
    runs-on: ubuntu-latest
    name: Docker Build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: ["build"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (Production)
        uses: docker/build-push-action@v6
        with:
          push: true
          context: apps/backend-rs
          platforms: linux/amd64
          tags: |
            ghcr.io/hikawi/foodbasket-api:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   name: Deploy
  #   needs: ["docker"]
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   concurrency:
  #     group: "backend"
  #     cancel-in-progress: false
  #   environment:
  #     name: Production
  #     url: https://api.foodbasket.app
  #   steps:
  #     - name: Deploy via SSH
  #       uses: appleboy/ssh-action@v1
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         password: ${{ secrets.SSH_PASSWORD }}
  #         script: |
  #           set -e

  #           cd /srv
  #           docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
  #           docker compose up -d --pull always foodbasket-api
  #           docker system prune -af
