name: FoodBasket Backend CI/CD

permissions:
  contents: write
  packages: write

on:
  push:
    paths:
      - apps/backend/**
  pull_request:
    paths:
      - apps/backend/**

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Don't truncate commit

      - uses: wagoid/commitlint-github-action@v6
        name: Commitlint

      - name: Setup dependencies
        run: sudo apt-get update && sudo apt-get install libvips-dev libvips-tools pkg-config

      - uses: actions/setup-go@v6
        name: Setup Go
        with:
          go-version-file: "./apps/backend/go.mod"
          cache-dependency-path: "apps/backend/go.sum"

      - name: Lint Golang
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6
          working-directory: apps/backend

  test:
    runs-on: ubuntu-latest
    name: Test
    needs: ["lint"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        name: Setup Go
        with:
          go-version-file: "./apps/backend/go.mod"
          cache-dependency-path: "apps/backend/go.sum"

      - name: Setup dependencies
        run: sudo apt-get update && sudo apt-get install libvips-dev libvips-tools pkg-config

      - name: Test
        run: go test ./... -cover
        working-directory: apps/backend

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: ["test"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        name: Setup Go 1.25.4
        with:
          go-version-file: "./apps/backend/go.mod"
          cache-dependency-path: "apps/backend/go.sum"

      - name: Setup dependencies
        run: sudo apt-get update && sudo apt-get install libvips-dev libvips-tools pkg-config

      - name: Build
        working-directory: apps/backend
        run: go build .

  docker:
    runs-on: ubuntu-latest
    name: Docker Build
    #if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: ["build"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (Production)
        uses: docker/build-push-action@v6
        with:
          push: true
          context: apps/backend
          platforms: linux/amd64
          tags: |
            ghcr.io/hikawi/foodbasket-api:latest

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: ["docker"]
    #if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    concurrency:
      group: "production"
      cancel-in-progress: false
    environment:
      name: Production
      url: https://api.foodbasket.luny.dev
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -e

            cd /srv
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker compose up -d --pull always foodbasket-api
            docker system prune -af

  # To be continued for when the project foundation, backend and frontend is setup.
