name: FoodBasket Frontend Admin CI/CD

permissions:
  contents: write
  packages: write

on:
  push:
    paths:
      - apps/frontend-admin/**
  pull_request:
    paths:
      - apps/frontend-admin/**

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commit Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: wagoid/commitlint-github-action@v6
        name: Commitlint

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: ["commitlint"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v6
        name: Setup Node
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Node dependencies
        working-directory: apps/frontend-admin
        run: pnpm i

      - name: Build
        working-directory: apps/frontend-admin
        run: pnpm build

  docker:
    runs-on: ubuntu-latest
    name: Docker Build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: ["build"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (Production)
        uses: docker/build-push-action@v6
        with:
          push: true
          context: apps/frontend-admin
          platforms: linux/amd64
          tags: |
            ghcr.io/hikawi/foodbasket-frontend-admin:latest

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: ["docker"]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    concurrency:
      group: "production"
      cancel-in-progress: false
    environment:
      name: Production
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -e

            cd /srv
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker compose up -d --pull always foodbasket-frontend-admin
            docker system prune -af
